const assert = require("node:assert/strict")
const files = require("../FileShareModel.js")
assert.equal(files.localPath("file:///tmp/r%C3%A9sum%C3%A9%20%23%3F%25%0A"), "/tmp/résumé #?%\n")
for (const url of ["https://host/file", "file://host/file", "file://localhost/file", "file:/tmp/a", "file:////remote/file", "file:///tmp/file?x", "file:///tmp/file#x", "file:///tmp/%00", "file:///tmp/%ff", "file:///tmp/%Q0", "file:///tmp/%", "file:///" + "😀".repeat(1024)])
  assert.equal(files.localPath(url), "", url)
assert.equal(files.localPath("file:///" + "a".repeat(4095)).length, 4096)
assert.equal(files.selection([]).ok, false)
assert.equal(files.selection(Array(33).fill("file:///tmp/a")).ok, false)
assert.equal(files.selection(["file:///tmp/a", "file:///tmp/%61"]).ok, false)
assert.equal(files.selection(["file:///tmp/a", "https://host/b"]).paths.length, 0)
assert.deepEqual(files.selection(["file:///tmp/a", "file:///tmp/b"]).paths, ["/tmp/a", "/tmp/b"])
const accepted = JSON.stringify({ok:true, state:"accepted", count:2, code:"accepted", statusText:"delivered"})
assert.equal(files.result(accepted, 0, 2).state, "accepted")
assert.match(files.result(accepted, 0, 2).text, /not verified/)
for (const [raw, exit, count] of [[accepted, 1, 2], [accepted, 0, 1], ["null", 0, 2], ["{}", 0, 2], ["not json", 0, 2], [accepted + "x".repeat(4096), 0, 2]])
  assert.equal(files.result(raw, exit, count).state, "unconfirmed")
assert.equal(files.result(JSON.stringify({ok:false,state:"failed",code:"offline",count:2}), 1, 2).state, "failed")
assert.equal(files.result(JSON.stringify({ok:false,state:"failed",code:"constructor",count:2}), 1, 2).state, "unconfirmed")
assert.equal(files.result(JSON.stringify({ok:false,state:"failed",code:"unknown",count:2}), 1, 2).state, "unconfirmed")
assert.equal(files.result(JSON.stringify({ok:false,state:"unconfirmed",code:"dispatch_unconfirmed",count:2}), 1, 2).state, "unconfirmed")
console.log("File sharing model tests passed")
